### ISSUE TITLE
Create Solution offers

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/marketplace#1]
As proposed by Denis some kind of marketplace should be introduced to Clarity, which would give solution providers an opportunity to promote their solutions, which would include different hazards, elements at risk and reference showcases.

For a first draft the following steps need to be done:

- [x] create 3 vocabularies (Hazards, Elements at risk, Solution offer types)

- [x] create 2 content types (Supported scenario, Showcase) with necessary view modes 

- [x] install module Paragraphs

- [x] create a View for the Entity Browser ("Entity Browser for Content")

- [x] create Entity Browser for "Supported scenario" and "Showcase"

- [x] create Paragraph "Solution offer reference" which links to showcases

- [x] create Group type "Solution offer"

- [x] create View for Solution offers overview page

- [x] add styling to subtheme

- [x] i18n support, see https://github.com/clarity-h2020/marketplace/issues/7

**Comment by p-a-s-c-a-l** [comment]
I've enabled i18n support and provided a translation for [this showcase](https://csis.myclimateservice.eu/node/488). Unfortunately, this showcase is not duplicated in the Map and the table:

![grafik](https://user-images.githubusercontent.com/1788226/57849493-b9c8d280-77db-11e9-8df9-48d1003c24b3.png)

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
reason for this duplication is that the views are not yet configured for usage with multiple languages. I configured the Twins-View so that it now displays content in the language set by the URL (.../**DE**/study/1/step/2/view/twins   for German) and falls back to the content in default language if no translation is available.

I think this behaviour could be used all over CSIS, but that's something we can further discuss during our next developer meeting.

**Comment by patrickkaleta** [comment]
Styling of solution offers was improved as a result of the new Clarity theme. Currently Solution offers don't need any other improvements
