### ISSUE TITLE
Create Project Content type on the Marketplace

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/marketplace#11]
We need a possibility for Customers to describe his project, so he can find experts or solutions providers who fit to his needs or they can find him.Creating a Study on the csis for this purpose seems to be an overkill.
Andrea and I propose a "project" content type on the Marketplace. AT least it should have fields which contain the same data as the Context Tab for a csis-study and the projects location.  If this is the case the project can have a "create study" button which will then create a Study with this data in the csis.
I think this being a content and no group is sufficient enough since souch a short description is nothing what needs cocreation between multiple users.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/csis-architecture/issues/5#issuecomment-493029823 for a conceptual description of the project content type.
