### ISSUE TITLE
Show content across all drupal instances

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/marketplace#12]
Profile informations, Solutions offer, show cases, and so on have to available on all Drupal instances (CSIS, Marketplace,Profile,..). There are two posibilites to archieve this goal:

1. Synchronise all content  over all instances or
2. Get content by REST and ajax where we need it.

To solution 1:
I found some modules which would do the job for 1 for us but they need an external pay service (https://www.drupal.org/project/entity_pilot)or relay on JSON API v1 while we already use v2 (https://www.drupal.org/project/entity_share). We can also archive the goal by using Drupal core functionality. The drawback of multiplicating content over the instances is, that we have an bigger maintenance workload since we have to do changes in structure on every instance: Changes in the content has also to be synchronized.  This will not be a problem at the beginning, but if the site grows keeping all the content synchronized can get a performance problem.

To solution 2:
If we fetch the content to show from the drupal instance it originates, we have only one point to maintain structure and there is no need to synchronize content. Since drupal views provides a REST Display, we can filter the content in the same way if it is on the same drupal instance. Only complicated qureies which require heavy use of relationships are not possible over drupal instances then. I think this can be overcome by using more links to other views. 

I prefer Solution  2 and already started to create a custom module, which allows embedding external content by a block or field.in an entity.

**Comment by p-a-s-c-a-l** [comment]
Thanks, imho Solution 2 is a reasonable choice.

**Comment by fgeyer16** [comment]
So the first Version of the remote content module is now available under https://github.com/fgeyer16/scc_remote_content
This is a private repo for know. 
@patrickkaleta @p-a-s-c-a-l @therter 
Since you three an me are the main active people in drupal you should have got an invitation to collaborate in this repo. So you can clone and test it (and check if the explaeinations are understandable...). For installation just clone the repo in the web/modules/custom directory of a drupal 8 installation.
If I missed somethging at the permissions on the repo and you can not access it please let me know.
Other way to get the module: 
 
[scc_remote_content-master (1).zip](https://github.com/clarity-h2020/marketplace/files/3149699/scc_remote_content-master.1.zip)

**Comment by patrickkaleta** [comment]
@fgeyer16 just had a quick look at it. Pulling from your private repository worked fine. For the sake of completeness I'd just like to mention that after cloning the module it also has to be enabled in the Modules section (name of the module is "Remote Content").

Not sure I understand the "id" field on the RemoteSource page and how to fill that one out.

**Comment by fgeyer16** [comment]
After a first feedback from @patrickkaleta I changed the configuration interface and the configuration handling in the background. The configuration pages move from /admin/config/system to /admin/config/services.
Since the module is not in wide use now I die not make a hook_update. so existing configurations will be lost un update.

[scc_remote_content.zip](https://github.com/clarity-h2020/marketplace/files/3171385/scc_remote_content.zip)
