### ISSUE TITLE
Cannot edit Organisation / Department

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#18]
TypeError: this._handles.disableSelection is not a functionresizable-min.js:4:4486

![organisation](https://user-images.githubusercontent.com/1788226/58416540-36806a00-8082-11e9-9129-50b12585899e.gif)

**Comment by fgeyer16** [comment]
I tried it now as pascal.dihe but it worked on FF and Chrome. So I need more info

User pascal.dihe? Browser? 
What where the steps before?

1. Logged in
2. clicked the edit tab. 
3. clicked the Organisation tab

or something other?

**Comment by p-a-s-c-a-l** [comment]
Sorry, the popup was silently blocked by uBlock (:
