### ISSUE TITLE
Create Expert Profiles

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#2]
Simplify and and implement Expert Profiles in profiles.myclimateservice.eu Drupal 8 instance and link with www.myclimateservice.eu and csis.myclimateservice.eu instances (Single-Sign-On).

**Comment by p-a-s-c-a-l** [comment]
#### Direct Personal Communication

![grafik](https://user-images.githubusercontent.com/1788226/57529875-3cfaac00-7336-11e9-9a01-1963ea119d2c.png)

Perhaps we could add a "Type" field (Mail, Mobile, Skype, ...).?

**Comment by Andrea4ad** [comment]
Good proposal! Mail, mobile, other (e.g. Skype)?
Best, 
Andrea

Von meinem iPhone gesendet

**Comment by fgeyer16** [comment]
I changed this to this
![Bildschirmfoto von »2019-05-13 09-31-25«](https://user-images.githubusercontent.com/25331450/57603424-fb4e4900-7561-11e9-8155-3480d0a2600f.png)

The channel is a select or other list. So if the user has a new other communication channel he can add it as well. This is just functionality if you want another design for this field we can discuss it.

**Comment by Andrea4ad** [comment]
I think we have a good status now to invite people to join.

**Comment by p-a-s-c-a-l** [comment]
> I think we have a good status now to invite people to join.

did anybody join?

**Comment by p-a-s-c-a-l** [comment]
> did anybody join?

**Comment by Andrea4ad** [comment]
we did not promote - marketplace concept completely reworked, under construction,
sneak preview:
![grafik](https://user-images.githubusercontent.com/46245522/66658755-6b144d00-ec42-11e9-8661-b27af4406ae0.png)

relevant matching, contextual content; CSIS integration mulling over...

**Comment by fgeyer16** [comment]
In principle user management is independent from profile.myclimateservices.eu. every page in SSO like the csis can define and assign roles to users locally and manually. 
If there is the need to assign roles dependent from fileds in the users profile on profile.myclimateservices.eu this is prepared on Profile and already used for the marketplace.

This is implemented by a taxonomy which can be mapped to local users roles during user synchronization.
