### ISSUE TITLE
Showcases and Solution Offers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#20]
"Showcase" and "Solution Offers" shall be maintained in Marketplace (& synchronized with CSIS).

1st step is to move the respective data from CSIS to Marketplace. Since I don't expect that the data models are identical (there are also many references to CSIS-only taxonomies), this is a manual task.

2nd step is to synchronise CSIS with Marketplace. However, how can this work if the data models are different? Furthermore, in CSIS, "Showcases" and "Solution Offers" will only be used for the "Twins Tab" (Scenario Transferability). AFAIK we have to assign some taxonomy terms to these entities to make the twins functionality work. That means, if you create a new "Solution Offers" in Marketplace, you would have to assign a CSIS taxonomy term, e.g. "Hazard".

**Comment by fgeyer16** [comment]
The EU-GL, Hazard and elements at risk taxonomies are also available on the marketplace. Adaption option are available on Marketplace as taxonomy as well. since matching projects with offers rely also on them.

The only challenge on syncing is that the taxonomies were not synced from marketplace to csis but the other way. So the module used for syncing can not lookup term ids from what it imported itself. But this can be solved in on way or other.

**Comment by p-a-s-c-a-l** [comment]
> this can be solved in on way or other.

Any work done here yet? Is this still relevant anyway?

**Comment by p-a-s-c-a-l** [comment]
@mattia-leone wrote:
> I attach [here](https://github.com/clarity-h2020/marketplace/files/4686819/schede.clarity_v4.pdf) the draft of the first projects to insert as showcases. The work is in progress, and I think we should be able to produce some 20-30 sheets like this until August, where each project has 2 or more pages depending on how many adaptation options it integrates.
I understand Andrea's point about "virtual organizations", but I feel that in this case it would be better to insert them in the CSIS as already done for Adaptation Options and Adaptation Strategies. If CSIS and Marketplace are synced as @fgeyer16 says it should be fine I guess, since they will appear in any case in both environments.

I assume this has to be put into marketplace? But for the Twins we need into in CSIS, too.
