### ISSUE TITLE
Provider/ Climate Services Usability Issues

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#23]
The layout of this screen could be improved:

![grafik](https://user-images.githubusercontent.com/1788226/73826573-50bc3b80-47fe-11ea-970c-b1c43febb12a.png)

**Comment by p-a-s-c-a-l** [comment]
It's not clear what is meant here by spatial coverage. Country, Region, ...? Atm, the input field doesn't seem to have any function. Difference between checkbox list and input field not clear.

![grafik](https://user-images.githubusercontent.com/1788226/73826719-8eb95f80-47fe-11ea-99a8-469e78da0bba.png)

**Comment by p-a-s-c-a-l** [comment]
Not clear what should be entered here. Projects? Partners?

![grafik](https://user-images.githubusercontent.com/1788226/73827121-4babbc00-47ff-11ea-9ba2-d0fe292fc2f9.png)

**Comment by p-a-s-c-a-l** [comment]
now this screen seems to be gone:

![grafik](https://user-images.githubusercontent.com/1788226/74324519-7493fa00-4d87-11ea-9e64-710a2c4b6c69.png)

Bug or Feature? 😃

**Comment by fgeyer16** [comment]
> now this screen seems to be gone:
> image
> Bug or Feature? smiley

Hm do you still have problems to see that widget? On my machine it is where it should be. So maybe a bug :-)
