### ISSUE TITLE
Opportunities Screen Usability Issues

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#25]
![grafik](https://user-images.githubusercontent.com/1788226/74314836-7903e700-4d76-11ea-8d41-6029a01d00bc.png)

"*edit project phases*" without function. It shouldn't be visible for users that don't have the right to edit the project.

**Comment by fgeyer16** [comment]
Edit link is now rendered in a mode which allows checking permissions and is only shown if edit permission exists.
